#load image into memory
preload = /home/user/path/wallpaper.jpg

#set the wallpaper
#specific wallpaper
wallpaper {
	monitor = eDP-1 #check monitor by hyprctl monitors
	path = /home/user/path/wallpaper.jpg
}

#Fallback
wallpaper {
	monitor = 
	path = /home/user/path/wallpaper.jpg
}
#set false if you dont want that text to appear on the bottom
splash = false
