###################
### MY PROGRAMS ###
###################

# Set programs that you use
$terminal = alacritty
$fileManager = thunar
$menu = wofi --show drun


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# exec-once = $terminal
# exec-once = nm-applet &
 exec-once = hyprlock -c ~/.config/hypr/hyprlock/hyprlock.conf
 exec-once =  hyprpaper
 exec-once = sleep 1 && pkill waybar; waybar -c ~/.config/waybar/scripts/config.jsonc -s ~/.config/waybar/scripts/style.css
 exec-once = alacritty --class alacritty-btop -e btop
 exec-once = hypridle


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
#Imp to 
env = QT_QPA_PLATFORMTHEME,qt6ct


