##############################
### WINDOWS AND WORKSPACES ###
##############################

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#MY BTOP WINDOW RULE
windowrule = float on, match:class alacritty-btop
windowrule = workspace 1, match:class alacritty-btop
windowrule = move 75% 70%, match:class alacritty-btop
windowrule = size 700 400, match:class alacritty-btop
windorule = below on, match:class alacritty-btop
